sudo: required
services: 
    - docker

before_install:
    - docker build -t tema14/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true tema14/docker-react npm run test -- --coverage
    
deploy:
    provider: openshift
    user: "$OPENSHIFT_USER"
    password: "$OPENSHIFT_PWD"
    domain: openshiftdomain